// <auto-generated />
using System;
using EfCorePlayground;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCorePlayground.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20200419153944_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.products_id_sequence", "'products_id_sequence', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCorePlayground.Model.Brand.Brand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("EfCorePlayground.Model.Category.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("_brandId")
                        .HasColumnName("BrandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_brandId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("_categoryId")
                        .HasColumnName("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "_categoryId");

                    b.HasIndex("_categoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.Comment", b =>
                {
                    b.HasOne("EfCorePlayground.Model.Product.Product", null)
                        .WithMany("_comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.Product", b =>
                {
                    b.HasOne("EfCorePlayground.Model.Brand.Brand", null)
                        .WithMany()
                        .HasForeignKey("_brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("EfCorePlayground.Model.Product.Image", "_images", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnName("Image")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("ProductImages");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("EfCorePlayground.Model.Product.ProductDetails", "_details", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("EfCorePlayground.Model.Product.Description", "_description", b2 =>
                                {
                                    b2.Property<int>("ProductDetailsProductId")
                                        .HasColumnType("int");

                                    b2.Property<string>("_value")
                                        .HasColumnName("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductDetailsProductId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductDetailsProductId");
                                });

                            b1.OwnsOne("EfCorePlayground.Model.Product.Name", "_name", b2 =>
                                {
                                    b2.Property<int>("ProductDetailsProductId")
                                        .HasColumnType("int");

                                    b2.Property<string>("_value")
                                        .IsRequired()
                                        .HasColumnName("Name")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProductDetailsProductId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductDetailsProductId");
                                });
                        });

                    b.OwnsOne("EfCorePlayground.Model.Product.Rating", "_rating", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int?>("_value")
                                .HasColumnName("Rating")
                                .HasColumnType("int");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("EfCorePlayground.Model.Product.Tag", "_tags", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnName("Tag")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("ProductTags");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.ProductCategory", b =>
                {
                    b.HasOne("EfCorePlayground.Model.Product.Product", null)
                        .WithMany("_categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCorePlayground.Model.Category.Category", null)
                        .WithMany()
                        .HasForeignKey("_categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EfCorePlayground.Model.Product.Review", b =>
                {
                    b.HasOne("EfCorePlayground.Model.Product.Product", null)
                        .WithOne("_review")
                        .HasForeignKey("EfCorePlayground.Model.Product.Review", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
